// Mocks generated by Mockito 5.0.17 from annotations
// in single_chat_practice/test/mock_practice_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:single_chat_practice/services/firebase_service.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [AuthInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthInterface extends _i1.Mock implements _i2.AuthInterface {
  MockAuthInterface() {
    _i1.throwOnMissingStub(this);
  }
}
